version: '3.1'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ../:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 8180:80
    depends_on:
      - php

  php:
    container_name: php
    build: ./php
    volumes:
      - ../:/var/www/html

  mysql:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./database/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: '123'

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8181:80
    environment:
      - PMA_ARBITRARY=1